---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "zookeeper.fullname" . }}
  namespace: kafka
  labels: 
    app: {{ template "zookeeper.name" . }}
    chart: {{ template "zookeeper.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:  
  - name: client
    port: {{ .Values.ports.client }}
    targetPort: client
    protocol: TCP
  selector:
    app: {{ template "zookeeper.name" . }}
    release: {{ .Release.Name }}
  sessionAffinity: None
