---
{{- if .Values.zookeeper.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.zookeeper.name" .  }}-headless
  namespace: {{ include "kafka.name" .  }}
  labels: 
  {{- include "kafka.zookeeper.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
{{ toYaml .Values.zookeeper.ports.client | indent 2 }}
{{ toYaml .Values.zookeeper.ports.election | indent 2 }}
{{ toYaml .Values.zookeeper.ports.server | indent 2 }}
  selector:
  {{- include "kafka.zookeeper.matchLabels" . | nindent 4 }}
  sessionAffinity: None
  type: ClusterIP
{{- end}}

