---
apiVersion: v1
kind: Pod
metadata:
  name: {{ include "kafka.name" . }}-internal-client
  namespace: {{ include "kafka.name" . }}
  labels:
    app: {{ include "kafka.name" . }}-internal-client
    chart: {{ include "kafka.name" . }} 
    release: {{ .Release.Name }}
spec:
  containers:
  - command:
    - sh
    - -c
    - exec tail -f /dev/null
    image: {{ .Value.images.client }}
    imagePullPolicy: {{ .Values.imagePullPolicy }}
    name: {{ include "kafka.name" . }}
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
