---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  labels:
    app: kafka-zookeeper
  name: kafka-zookeeper-budget
  namespace: kafka
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: kafka-zookeeper
