---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: kafka
spec:
  ports:
  - name: broker-internal
    port: 9092
    protocol: TCP
    targetPort: 9092
  - name: broker-external
    port: 9093
    protocol: TCP
    targetPort: 9093
  selector:
    app: kafka
  sessionAffinity: None
  type: ClusterIP

