---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: kafka
  name: kafka
  namespace: kafka
spec:
  podManagementPolicy: OrderedReady
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kafka
  serviceName: kafka-headless
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka-broker
        image: wurstmeister/kafka
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9093
          name: external
        - containerPort: 9092
          name: internal
        env:
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "kafka-zookeeper:2181"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "INTERNAL:PLAINTEXT,EXTERNAL:SSL"
        - name: KAFKA_LISTENERS
          value: "INTERNAL://:9092,EXTERNAL://:9093"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "INTERNAL://:9092,EXTERNAL://:9093"
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: "INTERNAL"
        - name: KAFKA_SSL_KEYSTORE_LOCATION
          value: "/var/private/ssl/kafka.server.keystore.jks"
        - name: KAFKA_SSL_KEYSTORE_PASSWORD
          value: "test1234"
        - name: KAFKA_SSL_TRUSTSTORE_LOCATION
          value: "/var/private/ssl/kafka.server.truststore.jks"
        - name: KAFKA_SSL_TRUSTSTORE_PASSWORD
          value: "test1234"
        - name: KAFKA_SSL_KEY_PASSWORD
          value: "test1234"
        - name: KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM
          value: ""
        - name: KAFKA_SSL_CLIENT_AUTH
          value: "required"
        - name: KAFKA_LOG_DIRS
          value: "/opt/kafka/data/logs"
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "3"
        - name: KAFKA_HEAP_OPTS
          value: "-Xmx1G -Xms1G"
        - name: KAFKA_PORT
          value: "9092"
        - name: KAFKA_DEFAULT_PARTITIONS
          value: '1'
        - name: KAFKA_DEFAULT_REPLICATION_FACTOR
          value: '3'
        - name: KAFKA_MIN_INSYNC_REPLICAS
          value: '2'
        - name: KAFKA_LOG4J_ROOT_LOGLEVEL
          value: DEBUG
        volumeMounts:
        - mountPath: /opt/kafka/data
          name: datadir
        - name: kafka-ssl
          mountPath: /var/private/ssl
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - name: datadir
        emptyDir: {}
      - name: kafka-ssl
        secret:
          secretName: kafka-ssl
          defaultMode: 420
  updateStrategy:
    type: RollingUpdate
