---
apiVersion: v1
kind: Service
metadata:
  name: kafka-lb-0
  namespace: kafka
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  externalIPs:
  - 192.168.99.115
  ports:
  - name: external 
    port: 9000
    targetPort: 9093
  selector:
    statefulset.kubernetes.io/pod-name: kafka-0
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-lb-1
  namespace: kafka
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  externalIPs:
  - 192.168.99.115
  ports:
  - name: external
    port: 9000
    targetPort: 9093
  selector:
    statefulset.kubernetes.io/pod-name: kafka-1
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-lb-2
  namespace: kafka
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  externalIPs:
  - 192.168.99.115
  ports:
  - name: external
    port: 9000
    targetPort: 9093
  selector:
    statefulset.kubernetes.io/pod-name: kafka-2
