---
apiVersion: v1
kind: Service
metadata:
  name: kafka-0
  labels:
    name: kafka-0
  namespace: kafka
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - port: 9092
    targetPort: 9092
    protocol: TCP
  externalIPs:
  - 192.168.99.108
  selector:
    statefulset.kubernetes.io/pod-name: kafka-0
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-1
  labels:
    name: kafka-1
  namespace: kafka
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - port: 9092
    targetPort: 9092
    protocol: TCP
  externalIPs:
  - 192.168.99.108
  selector:
    statefulset.kubernetes.io/pod-name: kafka-1
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: kafka
  namespace: kafka
spec:
  selector:
    matchLabels:
      app: kafka
  serviceName: "kafka"
  replicas: 2
  podManagementPolicy: OrderedReady
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: wurstmeister/kafka
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9092
          name: plaintext
        env:
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper-service:2181"
        - name: KAFKA_LISTENERS
          value: "PLAINTEXT://:9092"
