{{- if .Values.enableLoadBalancer }}
  {{- $brokers := .Values.replicas | int }}
  {{- $root := . }}
  {{- range $i, $e := until $brokers }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "kafka.fullname" $root }}-loadbalancer-{{ $i }}
  namespace: kafka
  labels:
    app: {{ include "kafka.name" $root }}
    chart: {{ template "kafka.chart" $root }}
    release: {{ $root.Release.Name }}
    heritage: {{ $root.Release.Service }}
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  externalIPs:
  - {{ $root.Values.externalIP }}
  ports:
  - name: external 
    port: {{ $root.Values.ports.exposed }}
    targetPort: {{ $root.Values.ports.external }}
  selector:
    app: {{ include "kafka.name" $root }}
    release: {{ $root.Release.Name }}
    statefulset.kubernetes.io/pod-name: {{ template "kafka.fullname" $root }}-{{ $i }}
  {{- end}}
{{- end}}
