---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "kafka.fullname" . }}-headless
  namespace: kafka
  labels:
    app: {{ template "kafka.name" . }}
    chart: {{ template "kafka.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  clusterIP: None
  ports:
  - name: internal
    port: {{ .Values.ports.internal }}
  selector:
    app: {{ template "kafka.name" . }}
    release: {{ .Release.Name }}
